<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.linecorp.bot.client.ExceptionConverterTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2017-10-29T06:18:45" hostname="gaohuaxuandeMacBook-Air.local" time="0.009">
  <properties/>
  <testcase name="convertTest" classname="com.linecorp.bot.client.ExceptionConverterTest" time="0.0"/>
  <testcase name="convertUnknownExceptionTest" classname="com.linecorp.bot.client.ExceptionConverterTest" time="0.001"/>
  <testcase name="exceptionInConvertFallbackedTest" classname="com.linecorp.bot.client.ExceptionConverterTest" time="0.008"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
